// Generated by CoffeeScript 1.8.0
(function() {
  seajs.config({
    base: 'http://product.astro.sina.com.cn/js/product/',
    paths: {},
    alias: {
      'utils': 'utils',
      'form': 'form',
      'network': 'network',
      'scrollpic': 'scrollpic',
      'slider': 'slider',
      'purchase': 'purchase.js?v=1.0.0',
      'underscore': 'lib/underscore-min.js',
      'wb': 'lib/weibo-all.js',
      'sinalib': 'lib/sinalib.js',
      'sweetalert': 'lib/sweet-alert.min.js',
      'userpanel': 'http://i.sso.sina.com.cn/js/user_panel.js',
      'outlogin_layer' : 'http://i.sso.sina.com.cn/js/outlogin_layer.js'
    }
  });

}).call(this);
